### ISSUE TITLE
Publish crate to crates.io

### ISSUE THREAD

**Issue by seanpianka** [logannc/fuzzywuzzy-rs#9]

**Comment by logannc** [comment]
https://crates.io/crates/fuzzywuzzy !

**Comment by seanpianka** [comment]
What's the process for releasing a new version of the crate, i.e. 0.2.3 for the next bug-fix or 0.3 when additional `process` methods are added?

**Comment by logannc** [comment]
We're actually at version 0.0.2. Given that it was a new crate, I chose the lowest possible version (0.0.1) when making the new crate. I chose this because I anticipate making breaking changes to the current methods. Because Python and Rust are sufficiently different, I will split some of the current methods with sane defaults where the equivalent python methods might have default kwargs.

I may also consider enum-based default arguments for more complicated ones (https://dev.to/virtualkirill/optional-arguments-in-rust-1e9g). e.g., the scorer or processor, maybe. I'm not sold on it yet.

As for the actual process, it's basically just `cargo publish` whenever we want.
